CREATE TABLE [dbo].[ArtistMusic]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY,
	[MusicId] INT NOT NULL,
	[ArtistID] INT NOT NULL,

	CONSTRAINT FK_ARTIST_MUSIC_ID FOREIGN KEY(MusicID)REFERENCES dbo.[Music](id),
	CONSTRAINT FK_MUSIC_ARTIST_ID FOREIGN KEY(ArtistID)REFERENCES dbo.[Artist](id),
)
