CREATE TABLE [dbo].[User_]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY, 
	[Pseudo] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(250) NOT NULL,
	[Password] VARBINARY(64) NOT NULL, 
	[Salt] VARCHAR(50) NOT NULL, 

	CONSTRAINT UK_PSEUDO UNIQUE ([Pseudo]),
	CONSTRAINT UK_EMAIL UNIQUE ([Email]),
	CONSTRAINT CK_EMAIL CHECK ([Email] LIKE '%@%.%')

)
